config/routes.rb
Rails.application.routes.draw do
  resources :statics
  resources :ingredients
  resources :menus
  resources :recipes
  resources :pantries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pantry.rb
class Pantry < ApplicationRecord
    belongs_to: user
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController
  before_action :set_pantry, only: %i[ show edit update destroy ]

  # GET /pantries or /pantries.json
  def index
    @pantries = Pantry.all
  end

  # GET /pantries/1 or /pantries/1.json
  def show
  end

  # GET /pantries/new
  def new
    @pantry = Pantry.new
  end

  # GET /pantries/1/edit
  def edit
  end

  # POST /pantries or /pantries.json
  def create
    @pantry = Pantry.new(pantry_params)

    respond_to do |format|
      if @pantry.save
        format.html { redirect_to @pantry, notice: "Pantry was successfully created." }
        format.json { render :show, status: :created, location: @pantry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pantries/1 or /pantries/1.json
  def update
    respond_to do |format|
      if @pantry.update(pantry_params)
        format.html { redirect_to @pantry, notice: "Pantry was successfully updated." }
        format.json { render :show, status: :ok, location: @pantry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pantries/1 or /pantries/1.json
  def destroy
    @pantry.destroy
    respond_to do |format|
      format.html { redirect_to pantries_url, notice: "Pantry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pantry
      @pantry = Pantry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pantry_params
      params.require(:pantry).permit(:ingredient_pauntry, :quantity_pauntry)
    end
end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/views/pantries/_form.html.erb
<%= form_with(model: pantry, local: true) do |form| %>
  <% if pantry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pantry.errors.count, "error") %> prohibited this pantry from being saved:</h2>

      <ul>
      <% pantry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ingredient_pauntry %>
    <%= form.text_field :ingredient_pauntry %>
  </div>

  <div class="field">
    <%= form.label :quantity_pauntry %>
    <%= form.text_field :quantity_pauntry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pantries/edit.html.erb
<h1>Editing Pantry</h1>

<%= render 'form', pantry: @pantry %>

<%= link_to 'Show', @pantry %> |
<%= link_to 'Back', pantries_path %>

app/views/pantries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pantries</h1>

<table>
  <thead>
    <tr>
      <th>Ingredient pauntry</th>
      <th>Quantity pauntry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pantries.each do |pantry| %>
      <tr>
        <td><%= pantry.ingredient_pauntry %></td>
        <td><%= pantry.quantity_pauntry %></td>
        <td><%= link_to 'Show', pantry %></td>
        <td><%= link_to 'Edit', edit_pantry_path(pantry) %></td>
        <td><%= link_to 'Destroy', pantry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pantry', new_pantry_path %>

app/views/pantries/new.html.erb
<h1>New Pantry</h1>

<%= render 'form', pantry: @pantry %>

<%= link_to 'Back', pantries_path %>

app/views/pantries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient pauntry:</strong>
  <%= @pantry.ingredient_pauntry %>
</p>

<p>
  <strong>Quantity pauntry:</strong>
  <%= @pantry.quantity_pauntry %>
</p>

<%= link_to 'Edit', edit_pantry_path(@pantry) %> |
<%= link_to 'Back', pantries_path %>