config/routes.rb
Rails.application.routes.draw do
  resources :statics
  resources :ingredients
  resources :menus
  resources :recipes
  resources :pantries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/static.rb
class Static < ApplicationRecord
    has_one :menu
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  before_action :set_static, only: %i[ show edit update destroy ]

  # GET /statics or /statics.json
  def index
    @statics = Static.all
  end

  # GET /statics/1 or /statics/1.json
  def show
  end

  # GET /statics/new
  def new
    @static = Static.new
  end

  # GET /statics/1/edit
  def edit
  end

  # POST /statics or /statics.json
  def create
    @static = Static.new(static_params)

    respond_to do |format|
      if @static.save
        format.html { redirect_to @static, notice: "Static was successfully created." }
        format.json { render :show, status: :created, location: @static }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statics/1 or /statics/1.json
  def update
    respond_to do |format|
      if @static.update(static_params)
        format.html { redirect_to @static, notice: "Static was successfully updated." }
        format.json { render :show, status: :ok, location: @static }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @static.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statics/1 or /statics/1.json
  def destroy
    @static.destroy
    respond_to do |format|
      format.html { redirect_to statics_url, notice: "Static was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static
      @static = Static.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_params
      params.require(:static).permit(:id_statics, :id_menu, :count_menu, :score_menu)
    end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/_form.html.erb
<%= form_with(model: static, local: true) do |form| %>
  <% if static.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static.errors.count, "error") %> prohibited this static from being saved:</h2>

      <ul>
      <% static.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_statics %>
    <%= form.number_field :id_statics %>
  </div>

  <div class="field">
    <%= form.label :id_menu %>
    <%= form.number_field :id_menu %>
  </div>

  <div class="field">
    <%= form.label :count_menu %>
    <%= form.number_field :count_menu %>
  </div>

  <div class="field">
    <%= form.label :score_menu %>
    <%= form.number_field :score_menu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statics/edit.html.erb
<h1>Editing Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Show', @static %> |
<%= link_to 'Back', statics_path %>

app/views/statics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statics</h1>

<table>
  <thead>
    <tr>
      <th>Id statics</th>
      <th>Id menu</th>
      <th>Count menu</th>
      <th>Score menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statics.each do |static| %>
      <tr>
        <td><%= static.id_statics %></td>
        <td><%= static.id_menu %></td>
        <td><%= static.count_menu %></td>
        <td><%= static.score_menu %></td>
        <td><%= link_to 'Show', static %></td>
        <td><%= link_to 'Edit', edit_static_path(static) %></td>
        <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<h1>New Static</h1>

<%= render 'form', static: @static %>

<%= link_to 'Back', statics_path %>

app/views/statics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id statics:</strong>
  <%= @static.id_statics %>
</p>

<p>
  <strong>Id menu:</strong>
  <%= @static.id_menu %>
</p>

<p>
  <strong>Count menu:</strong>
  <%= @static.count_menu %>
</p>

<p>
  <strong>Score menu:</strong>
  <%= @static.score_menu %>
</p>

<%= link_to 'Edit', edit_static_path(@static) %> |
<%= link_to 'Back', statics_path %>